# -*- coding: utf-8 -*-
"""PySpark.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PlqdIvWqlyKJs414lhW92swBSwWmnKjN
"""

!apt-get install openjdk-8-jdk-headless -qq > /dev/null

!wget -q https://mirror.olnevhost.net/pub/apache/spark/spark-2.4.5/spark-2.4.5-bin-hadoop2.7.tgz

!tar xf spark-2.4.5-bin-hadoop2.7.tgz

!pip install -q findspark

!ls /usr/lib/jvm
!pwd

import os
os.environ["JAVA_HOME"]="/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"]="/content/spark-2.4.5-bin-hadoop2.7"

!echo $JAVA_HOME

import findspark
findspark.init()
from pyspark.sql import SparkSession

spark = SparkSession.builder.master("local[*]").getOrCreate()

spark.conf.set("spark.executor.memory","4g")
spark.conf.set("spark.driver.memory","4g")
spark.conf.set("spark.memory.fraction","4g")

!pip install -U pyarrow

import sys, urllib,tempfile

Base_Dir = '/tmp'
OUTPUT_FILE = os.path.join(Base_Dir,"credit_data.csv")

credit_data = urllib.request.urlretrieve("https://archive.ics.uci.edu/ml/machine-learning-databases/credit-screening/crx.data",OUTPUT_FILE)

!ls

credit_df = spark.read.option("inferSchema","true").csv("/tmp/credit_data.csv", header=False)

credit_df.show()

credit_df.count()



!git remote add origin https://github.com/varshachawan/PySparkApplication.git

!git push -u origin master

!git config — global user.email “varsharanichawan@gmail.com”

!git config — global user.name “varshachawan”

!git add /content/PySpark.ipynb

!pwd

